

apiVersion: networking.k8s.io/v1

kind: Ingress
metadata:
  name: mongo-express

spec:

  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongo-express
                port:
                  number: 8081
  {{- end }}
